<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MAS.Application\MAS.Application.csproj" />
    <ProjectReference Include="..\MAS.Core\MAS.Core.csproj" />
    <ProjectReference Include="..\MAS.Infrastructure\MAS.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
